apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neptune-web
  namespace: neptune
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - neptune.local
      secretName: neptune-tls
  rules:
    - host: neptune.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: neptune-web
                port:
                  number: 80

