apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap-app.yaml
  - postgres/postgres-statefulset.yaml
  - postgres/postgres-service.yaml
  - postgres/postgres-pdb.yaml
  - postgres/postgres-np.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/hpa.yaml
  - backend/pdb.yaml
  - backend/networkpolicy.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/ingress.yaml
  - frontend/networkpolicy.yaml

