apiVersion: v1
kind: ServiceAccount
metadata:
  name: neptune-sa
  namespace: neptune
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: neptune-read-config
  namespace: neptune
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: neptune-bind
  namespace: neptune
subjects:
  - kind: ServiceAccount
    name: neptune-sa
roleRef:
  kind: Role
  name: neptune-read-config
  apiGroup: rbac.authorization.k8s.io

