# Copy this to secret-app.yaml and edit before applying
apiVersion: v1
kind: Secret
metadata:
  name: neptune-secrets
  namespace: neptune
stringData:
  DB_USER: "neptune_user"
  DB_PASSWORD: "neptune@123"

